server:
    port: 8080
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka
    instance:
        hostname: localhost

spring:
    cloud:
        gateway:
            default-filters:
                - TokenRelay
            discovery:
                locator:
                    enabled: true
            routes:
                - id: users-service
                  uri: lb://users-service
                  predicates:
                      - Path=/users/**
                  filters:
                      - RemoveRequestHeader=Cookie
                - id: cars-service
                  uri: lb://cars-service
                  predicates:
                      - Path=/cars/**
                - id: bikes-service
                  uri: lb://bikes-service
                  predicates:
                      - Path=/bikes/**
    security:
        oauth2:
            client:
                provider:
                    keycloak:
                        authorizationUri: http://localhost:18080/realms/tutorial-microservicios-realm/protocol/openid-connect/auth
                        userInfoUri: http://localhost:18080/realms/tutorial-microservicios-realm/protocol/openid-connect/userinfo
                        userNameAttribute: preferred_username
                        tokenUri: http://localhost:18080/realms/tutorial-microservicios-realm/protocol/openid-connect/token
                registration:
                    tutorial-microservicios-client:
                        provider: keycloak
                        client-id: tutorial-microservicios-client
                        client-secret: AXdBWG81Ggof3TsDb20988uA2OIrOtM7
                        authorization-grant-type: authorization_code
                        redirect-uri: "{baseUrl}/login/oauth2/code/tutorial-microservicios-client"
