server:
    port: 8081
spring:
    application:
      name: config-service
    cloud:
        config:
            server:
                git:
                    default-label: feature/keycloak
                    uri: https://github.com/JoseMRocamora/tutorial.microservicios
                    search-paths:
                      - config-data
